POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Mary_S",
   "number":"12345"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Bob Marly",
   "number":"77777"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"",
   "number":"77877"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Bob Marly",
   "number":""
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Ada Lovelace",
   "number":"6897"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Bob Marly",
   "number":"39-44-5323523"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Alice Freindlihe",
   "number":"39-88-55"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Fu",
   "number":"3955"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Fudji",
   "number":"3955-0000"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Thomas",
   "number":"897569-00"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Thomas Mann",
   "number":"897"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Mann",
   "number":"897-27-36"
}
###
POST http://localhost:3001/api/persons
content-type: application/json

{
   "name":"Mann",
   "number":"897-256398"
}